export const deck2_1 = [
  { value: 7, suit: 'diamonds' },
  { value: 11, suit: 'clubs' },
  { value: 12, suit: 'spades' },
  { value: 10, suit: 'diamonds' },
  { value: 11, suit: 'spades' },
  { value: 10, suit: 'spades' },
  { value: 14, suit: 'diamonds' },
  { value: 12, suit: 'diamonds' },
  { value: 11, suit: 'hearts' },
  { value: 4, suit: 'clubs' },
  { value: 8, suit: 'spades' },
  { value: 5, suit: 'clubs' },
  { value: 7, suit: 'clubs' },
  { value: 13, suit: 'hearts' },
  { value: 3, suit: 'clubs' },
  { value: 6, suit: 'spades' },
  { value: 9, suit: 'diamonds' },
  { value: 3, suit: 'spades' },
  { value: 7, suit: 'hearts' },
  { value: 8, suit: 'diamonds' },
  { value: 9, suit: 'hearts' },
  { value: 10, suit: 'clubs' },
  { value: 13, suit: 'clubs' },
  { value: 6, suit: 'diamonds' },
  { value: 7, suit: 'spades' },
  { value: 8, suit: 'clubs' },
  { value: 12, suit: 'clubs' },
  { value: 13, suit: 'diamonds' },
  { value: 2, suit: 'hearts' },
  { value: 12, suit: 'hearts' },
  { value: 5, suit: 'hearts' },
  { value: 14, suit: 'hearts' },
  { value: 8, suit: 'hearts' },
  { value: 14, suit: 'clubs' },
  { value: 2, suit: 'spades' },
  { value: 3, suit: 'hearts' },
  { value: 6, suit: 'hearts' },
  //flop
  { value: 5, suit: 'diamonds' },
  { value: 5, suit: 'spades' },
  { value: 10, suit: 'hearts' },
  { value: 9, suit: 'spades' },
  { value: 11, suit: 'diamonds' },
  //p4
  { value: 13, suit: 'spades' },
  { value: 4, suit: 'diamonds' },
  //p3
  { value: 6, suit: 'clubs' },
  { value: 4, suit: 'spades' },
  //p2
  { value: 9, suit: 'clubs' },
  { value: 2, suit: 'clubs' },
  //p1
  { value: 3, suit: 'diamonds' },
  { value: 4, suit: 'hearts' },
  //p0
  { value: 14, suit: 'spades' },
  { value: 2, suit: 'diamonds' }
]
export const deck2_1_1 =[
  { value: 4, suit: 'spades' },
  { value: 5, suit: 'hearts' },
  { value: 12, suit: 'hearts' },
  { value: 3, suit: 'diamonds' },
  { value: 8, suit: 'hearts' },
  { value: 7, suit: 'spades' },
  { value: 7, suit: 'hearts' },
  { value: 8, suit: 'diamonds' },
  { value: 9, suit: 'hearts' },
  { value: 8, suit: 'clubs' },
  { value: 6, suit: 'diamonds' },
  { value: 2, suit: 'diamonds' },
  { value: 11, suit: 'diamonds' },
  { value: 9, suit: 'diamonds' },
  { value: 3, suit: 'clubs' },
  { value: 6, suit: 'clubs' },
  { value: 14, suit: 'diamonds' },
  { value: 9, suit: 'spades' },
  { value: 13, suit: 'hearts' },
  { value: 3, suit: 'hearts' },
  { value: 6, suit: 'spades' },
  { value: 12, suit: 'clubs' },
  { value: 13, suit: 'spades' },
  { value: 9, suit: 'clubs' },
  { value: 10, suit: 'diamonds' },
  { value: 2, suit: 'hearts' },
  { value: 11, suit: 'spades' },
  { value: 10, suit: 'hearts' },
  { value: 14, suit: 'spades' },
  { value: 14, suit: 'hearts' },
  { value: 4, suit: 'diamonds' },
  { value: 13, suit: 'diamonds' },
  { value: 13, suit: 'clubs' },
  { value: 11, suit: 'hearts' },
  { value: 8, suit: 'spades' },
  { value: 11, suit: 'clubs' },
  { value: 2, suit: 'clubs' },
  //flop
  { value: 5, suit: 'clubs' },
  { value: 14, suit: 'clubs' },
  { value: 7, suit: 'clubs' },
  { value: 5, suit: 'diamonds' },
  { value: 12, suit: 'diamonds' },
  //p4
  { value: 10, suit: 'spades' },
  { value: 2, suit: 'spades' },
  //p3
  { value: 10, suit: 'clubs' },
  { value: 5, suit: 'spades' },
  //p2
  { value: 6, suit: 'hearts' },
  { value: 7, suit: 'diamonds' },
  //p1
  { value: 4, suit: 'hearts' },
  { value: 12, suit: 'spades' },
  //p0
  { value: 3, suit: 'spades' },
  { value: 4, suit: 'clubs' }
]
export const deck2_1_2 = [
  { value: 3, suit: 'hearts' },
  { value: 2, suit: 'clubs' },
  { value: 2, suit: 'hearts' },
  { value: 14, suit: 'clubs' },
  { value: 2, suit: 'diamonds' },
  { value: 9, suit: 'clubs' },
  { value: 7, suit: 'clubs' },
  { value: 11, suit: 'hearts' },
  { value: 9, suit: 'hearts' },
  { value: 12, suit: 'hearts' },
  { value: 10, suit: 'diamonds' },
  { value: 8, suit: 'spades' },
  { value: 5, suit: 'hearts' },
  { value: 11, suit: 'clubs' },
  { value: 12, suit: 'clubs' },
  { value: 6, suit: 'clubs' },
  { value: 12, suit: 'spades' },
  { value: 9, suit: 'diamonds' },
  { value: 13, suit: 'clubs' },
  { value: 7, suit: 'spades' },
  { value: 2, suit: 'spades' },
  { value: 9, suit: 'spades' },
  { value: 8, suit: 'clubs' },
  { value: 4, suit: 'diamonds' },
  { value: 6, suit: 'spades' },
  { value: 13, suit: 'hearts' },
  { value: 8, suit: 'hearts' },
  { value: 6, suit: 'diamonds' },
  { value: 14, suit: 'diamonds' },
  { value: 5, suit: 'clubs' },
  { value: 13, suit: 'spades' },
  { value: 5, suit: 'diamonds' },
  { value: 12, suit: 'diamonds' },
  { value: 3, suit: 'spades' },
  { value: 14, suit: 'spades' },
  { value: 3, suit: 'diamonds' },
  { value: 4, suit: 'hearts' },
  //flop
  { value: 4, suit: 'clubs' },
  { value: 13, suit: 'diamonds' },
  { value: 6, suit: 'hearts' },
  { value: 8, suit: 'diamonds' },
  { value: 5, suit: 'spades' },
  //p4
  { value: 10, suit: 'hearts' },
  { value: 7, suit: 'hearts' },
  //p3
  { value: 11, suit: 'spades' },
  { value: 3, suit: 'clubs' },
  //p2
  { value: 4, suit: 'spades' },
  { value: 10, suit: 'clubs' },
  //p1
  { value: 14, suit: 'hearts' },
  { value: 10, suit: 'spades' },
  //p0
  { value: 11, suit: 'diamonds' },
  { value: 7, suit: 'diamonds' }
]
export const deck2_1_3 = [
  { value: 12, suit: 'spades' },
  { value: 2, suit: 'clubs' },
  { value: 14, suit: 'diamonds' },
  { value: 13, suit: 'diamonds' },
  { value: 8, suit: 'hearts' },
  { value: 10, suit: 'diamonds' },
  { value: 8, suit: 'clubs' },
  { value: 9, suit: 'diamonds' },
  { value: 3, suit: 'spades' },
  { value: 6, suit: 'clubs' },
  { value: 10, suit: 'hearts' },
  { value: 7, suit: 'hearts' },
  { value: 12, suit: 'hearts' },
  { value: 6, suit: 'hearts' },
  { value: 5, suit: 'diamonds' },
  { value: 11, suit: 'hearts' },
  { value: 9, suit: 'hearts' },
  { value: 5, suit: 'clubs' },
  { value: 4, suit: 'diamonds' },
  { value: 10, suit: 'spades' },
  { value: 14, suit: 'hearts' },
  { value: 11, suit: 'diamonds' },
  { value: 8, suit: 'diamonds' },
  { value: 2, suit: 'spades' },
  { value: 5, suit: 'hearts' },
  { value: 6, suit: 'spades' },
  { value: 2, suit: 'diamonds' },
  { value: 4, suit: 'hearts' },
  { value: 13, suit: 'hearts' },
  { value: 3, suit: 'hearts' },
  { value: 12, suit: 'clubs' },
  { value: 4, suit: 'spades' },
  { value: 9, suit: 'spades' },
  { value: 3, suit: 'clubs' },
  { value: 4, suit: 'clubs' },
  { value: 14, suit: 'clubs' },
  { value: 7, suit: 'clubs' },
  //flop
  { value: 7, suit: 'spades' },
  { value: 9, suit: 'clubs' },
  { value: 11, suit: 'clubs' },
  { value: 7, suit: 'diamonds' },
  { value: 10, suit: 'clubs' },
  //p4
  { value: 5, suit: 'spades' },
  { value: 6, suit: 'diamonds' },
  //p3
  { value: 14, suit: 'spades' },
  { value: 2, suit: 'hearts' },
  //p2
  { value: 4, suit: 'spades' },
  { value: 11, suit: 'diamonds' },
  //p1
  { value: 12, suit: 'spades' },
  { value: 12, suit: 'clubs' },
  //p0
  { value: 12, suit: 'diamonds' },
  { value: 12, suit: 'hearts' }
]
export const deck2_1_4 = [
  { value: 12, suit: 'hearts' },
  { value: 9, suit: 'spades' },
  { value: 8, suit: 'spades' },
  { value: 5, suit: 'clubs' },
  { value: 8, suit: 'hearts' },
  { value: 9, suit: 'clubs' },
  { value: 11, suit: 'diamonds' },
  { value: 3, suit: 'clubs' },
  { value: 12, suit: 'clubs' },
  { value: 14, suit: 'diamonds' },
  { value: 11, suit: 'hearts' },
  { value: 13, suit: 'clubs' },
  { value: 13, suit: 'spades' },
  { value: 5, suit: 'diamonds' },
  { value: 10, suit: 'hearts' },
  { value: 14, suit: 'spades' },
  { value: 6, suit: 'diamonds' },
  { value: 4, suit: 'clubs' },
  { value: 3, suit: 'diamonds' },
  { value: 2, suit: 'diamonds' },
  { value: 10, suit: 'spades' },
  { value: 2, suit: 'spades' },
  { value: 3, suit: 'spades' },
  { value: 13, suit: 'hearts' },
  { value: 6, suit: 'hearts' },
  { value: 14, suit: 'hearts' },
  { value: 4, suit: 'diamonds' },
  { value: 8, suit: 'diamonds' },
  { value: 12, suit: 'spades' },
  { value: 14, suit: 'clubs' },
  { value: 7, suit: 'hearts' },
  { value: 7, suit: 'diamonds' },
  { value: 4, suit: 'spades' },
  { value: 3, suit: 'hearts' },
  { value: 12, suit: 'diamonds' },
  { value: 11, suit: 'spades' },
  { value: 7, suit: 'spades' },
  { value: 10, suit: 'diamonds' },
  { value: 7, suit: 'clubs' },
  //flop
  { value: 10, suit: 'clubs' },
  { value: 8, suit: 'clubs' },
  { value: 7, suit: 'clubs' },
  { value: 6, suit: 'spades' },
  { value: 13, suit: 'diamonds' },
 
  //p3
  { value: 11, suit: 'hearts' },
  { value: 2, suit: 'diamonds' },
  //p2
  { value: 5, suit: 'hearts' },
  { value: 9, suit: 'clubs' },
  //p1
  { value: 10, suit: 'spades' },
  { value: 9, suit: 'hearts' },
  //p0
  { value: 2, suit: 'diamonds' },
  { value: 2, suit: 'clubs' }
]